### ISSUE TITLE
cmake/Modules/*.cmake licensing?

### ISSUE THREAD

**Issue by ppentchev** [rpm-software-management/createrepo_c#106]
Hi,

First of all, thanks a lot for writing and maintaining createrepo_c!

I'm in the process of packaging it for Debian and I stumbled upon a little problem: although most of the source files have a prominent copyright notice and GPL-2+ license grant, there are a couple of files in the cmake/Modules/ directory that mention licenses that do not have their terms fully stated:
- cmake/Modules/FindGLIB2.cmake, cmake/Modules/FindGTHREAD2.cmake, and cmake/Modules/FindSqlite3.cmake mention a BSD license (or in the case of the two former files, a "New BSD" license) and "the accompanying COPYING-CMAKE-SCRIPTS file", but there is no such file and the license terms are not stated at all, which, with a license in the BSD family, is kind of ambiguous (there are several versions of those)
- cmake/Modules/FindLibmagic.cmake mentions "licensed under the LGPL license", but does not have the usual "free software, distributed in the hope that it would be useful, should have received, etc, etc" blurb.  Also, it was added to the createrepo_c source repository along with another file, cmake/Modules/LibFindMacros.cmake, which does not have either a copyright notice or a license grant at all - since they were added together and FindLibmagic.cmake includes LibFindMacros.cmake, I assume that they have the same provenance, but still it might be better to be sure.

Thanks again for working on createrepo_c, and sorry to bother you with such trivialities!

G'luck,
Peter

**Comment by kenhys** [comment]
It seems that:

* cmake/Modules/FindGLIB2.cmake
  * Copyright is updated, it follows like https://github.com/KDE/extra-cmake-modules/blob/master/find-modules/FindGLIB2.cmake
* cmake/Modules/FindGTHREAD2.cmake
  * Copyrigtht is updated, too.

**Comment by kenhys** [comment]
* cmake/Modules/LibFindMacros.cmake
   * It seems that this is derived  from https://github.com/Tronic/cmake-modules/commit/5731f5b01a8b11d58c0cac97434136f7591c995b#diff-310118fcd460df1e7672a95065bdefe7
     which is linked from https://gitlab.kitware.com/cmake/community/-/wikis/doc/tutorials/How-To-Find-Libraries#using-libfindmacros

In this version copyright is noted as public domain:

```

# Version 1.0 (2013-04-12)
# Public Domain, originally written by Lasse Kärkkäinen <tronic@zi.fi>
# Published at http://www.cmake.org/Wiki/CMake:How_To_Find_Libraries

# If you improve the script, please modify the forementioned wiki page because
# I no longer maintain my scripts (hosted as static files at zi.fi). Feel free
# to remove this entire header if you use real version control instead.

# Changelog:
# 2013-04-12  Added version number (1.0) and this header, no other changes
# 2009-10-08  Originally published

```
