### ISSUE TITLE
Message: posix_spawn avoided (fd close requested)

### ISSUE THREAD

**Issue by AkiraNorthstar** [rpm-software-management/createrepo_c#107]
Hello!
Since I installed Fedora 29, I get the following message when using createrepo_c:
```bash
sudo createrepo_c --update RPMS/x86_64/
Directory walk started
Directory walk done - 12 packages
Loaded information about 12 packages
Temporary output repo path: RPMS/x86_64/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished
13:05:17: posix_spawn avoided (fd close requested) 
13:05:17: posix_spawn avoided (fd close requested) 
13:05:17: posix_spawn avoided (fd close requested) 
13:05:17: posix_spawn avoided (fd close requested) 
```
Version:
```
sudo createrepo_c --version
Version: 0.11.1 (Features: DeltaRPM LegacyWeakdeps )
```

Even if I execute this command inside a docker container, I get this message about posix_spawn avoided.
This message does not appear under fedora 28 (real install) and fedora 28 docker installation.

Is this just a hint or an error message?

**Comment by duritong** [comment]
This message is breaking mockchain: rpm-software-management/mock#227

**Comment by phmccarty** [comment]
The discussion on this glib merge request provides more details on the issue:

https://gitlab.gnome.org/GNOME/glib/merge_requests/337

**Comment by AkiraNorthstar** [comment]
Thanks for the answers and the hints!
I'm not alone with this message .... ;-)

**Comment by limburgher** [comment]
I got this on 0.14.1.

**Comment by limburgher** [comment]
0.12.2 works.

**Comment by kontura** [comment]
I am not able to reproduce this on any recent version in fedora.
Looks like it was a problem in glib.

Please reopen this if its still an issue.
