### ISSUE TITLE
checkts / -C compatibility missing

### ISSUE THREAD

**Issue by alpeshspatel** [rpm-software-management/createrepo_c#130]
Hello,

Missing --checkts flag functionality.

Details:
createrepo implementation is the --checkts flag, that when used together with --update and --read-pkgs-list  <listfile> , outputs just the list of packages that were considered in the current run. the <listfile> will have the list of the updated packages.

Without the --checkts flag, I see that when using --update and ----read-pkgs-list <listfile> , <listfile> has the full list of rpms in the repository and not just the ones that have changed. 

How to find the list of RPMs that were modified (e.g added to repo) since last run of createrepo_c

**Comment by kontura** [comment]
The --checkts flag does actually something little bit different in the original createrepo and doesn't have anything to do with the list --read-pkgs-list generates. I have even tested it and it has no effect on the list.

However you are right that --read-pkgs-list with --update doesn't work in createrepo_c. It is always showing a full list of all processed packages. I have created a PR https://github.com/rpm-software-management/createrepo_c/pull/170 that should fix this problem and the resulting list will only contains packages actually read (as it says in the man page).
