### ISSUE TITLE
mergerepo needs to support merging module metadata

### ISSUE THREAD

**Issue by sgallagher** [rpm-software-management/createrepo_c#131]
We need to handle cases where a user has built a module repository (such as by using MBS local builds) and wants to add it to an existing repo (such as a company-internal repository).

What mergerepo_c needs to do is this:
* Link against libmodulemd
* Use libmodulemd routines to read in the modules.yaml from the source repo
* Read in the modules.yaml from the additive repo(s)
* Use the ModuleIndexMerger functionality to merge the two sets of metadata
* Write the metadata YAML back out and store it.

Documentation: https://sgallagh.fedorapeople.org/docs/libmodulemd/latest/modulemd-2.0-Modulemd.ModuleIndexMerger.html

**Comment by Conan-Kudo** [comment]
This should be supported now in v0.13.0.
