### ISSUE TITLE
Add native support for module metadata

### ISSUE THREAD

**Issue by sgallagher** [rpm-software-management/createrepo_c#134]
Rather than using the `--mdtype` argument to `modifyrepo_c`, it needs to be possible to have createrepo_c accept a modulemd as standard input. This will be a necessary prerequisite to #132

**Comment by sgallagher** [comment]
Quite a bit of discussion on this has occurred during the code review of #146 with @Conan-Kudo 

Capturing some of it here for future reference:

> @Conan-Kudo Would you mind spelling out what you see as the validation cases (and what should happen if there's a discrepancy)?
> 
> Here are the cases I can think of:
> 
> ## Prerequisites
> A modulemd YAML document is provided to createrepo_c that contains a mixture of zero or more
> * Module Stream documents
> * Module Default documents
> * Module Translation documents
> 
> ## Case 1: Entirely valid modulemd
> Conditions:
> * Module Stream documents: all entries in the `data.artifacts.rpms` section match RPM filenames in the repository being manipulated
> * Module Default documents: all defaults reference a module for which there is at least one Module Stream document in the stream.
> * Module Translation documents: all translations reference a module for which there is at least one Module Stream document in the stream.
> 
> This is the absolute easiest case. This modulemd YAML should be preserved in its entirety.
> 
> ## Case 2: Some missing artifacts
> Conditions:
> * Module Stream documents: One or more of these documents have some entries in the `data.artifacts.rpms` section that are not reflected in the repository and some that are.
> * Module Default documents: all defaults reference a module for which there is at least one Module Stream document in the stream.
> * Module Translation documents: all translations reference a module for which there is at least one Module Stream document in the stream.
> 
> Do we filter out this module stream object or assume that as long as at least one item in the artifacts list is present that we should keep this stream document? I think the latter, since to do otherwise means that such artifacts would then be viewed by DNF as if they were non-modular and therefore considered for updates where they should not be.
> 
> ## Case 3: All missing artifacts
> Conditions:
> * Module Stream documents: One or more of these documents have their `data.artifacts.rpms` section containing no artifacts that match the contents of the repository.
> * Module Default documents: all defaults reference a module for which there is at least one Module Stream document in the stream.
> * Module Translation documents: all translations reference a module for which there is at least one Module Stream document in the stream.
> 
> In this case, do we filter the offending Module Stream document(s) out of the final output?
> 
> ## Case 4: Defaults with no matching stream
> * Module Stream documents: all entries in the `data.artifacts.rpms` section match RPM filenames in the repository being manipulated
> * Module Default documents: One or more such documents do not reference a module stream present in the metadata.
> * Module Translation documents: all translations reference a module for which there is at least one Module Stream document in the stream.
> 
> In this situation, I think we still need to preserve the defaults, because this may be a metadata-only change (such as a case where the `fedora` repository contains a module stream and later we modify the stream defaults to treat that stream as the default. This doesn't require a rebuild of the module stream, so it may not be present in the updates repo.
> 
> ## Case 5: Translations with no matching stream
> * Module Stream documents: all entries in the `data.artifacts.rpms` section match RPM filenames in the repository being manipulated
> * Module Default documents: all defaults reference a module for which there is at least one Module Stream document in the stream.
> * Module Translation documents: one or more translations reference modules not represented in this YAML stream.
> 
> In this situation, I think we still need to preserve the translations, because this may be a metadata-only change (such as a case where the `fedora` repository contains a module stream and the only change to it is to add new translations. This doesn't require a rebuild of the module stream, so it may not be present in the updates repo.


@Conan-Kudo replied:

> @sgallagher
> 
> Case 1 is fine. My concern with case 2 is that I don't know how it would be handled for modulemd aware reposyncs. In my view, if a component is missing, then it should be dropped from the metadata, because otherwise it'll look like the component is there when it isn't.
> 
> Cases 3, 4, and 5 should result in the module document getting dropped. What is the point of keeping a document that has no underlying content? It bloats the metadata for essentially no reason.


And I responded with:

> > @sgallagher
> > Case 1 is fine. My concern with case 2 is that I don't know how it would be handled for modulemd aware reposyncs. In my view, if a component is missing, then it should be dropped from the metadata, because otherwise it'll look like the component is there when it isn't.
> 
> The problem with dropping the metadata in that situation is that we may end up with a repo that has modular RPMs that are treated by DNF as non-modular RPMs (meaning that stream filtering doesn't happen). This _will_ cause issues.
> 
> Maybe we should just agree this is a hard failure for the createrepo operation and that if we end up with only a partial match, we assume that the repo was not properly populated. Reasonable?
> 
> > Cases 3, 4, and 5 should result in the module document getting dropped. What is the point of keeping a document that has no underlying content? It bloats the metadata for essentially no reason.
> 
> Case 3, I agree with. If we have zero of the artifacts referenced for a stream, let's just drop that from the metadata. That will make life easier for filtering things out if we want to trim a repository.
> 
> For cases 4 and 5, I tried to explain in the original comment, but my view is that these are _valid_ cases that we cannot reasonably be able to detect, short of duplicating data unnecessarily. It is completely reasonable that we might ship nodejs:10 as a module in Fedora 30's frozen `fedora` repository. Then, later in F30's life, we complete the default-modules-in-the-non-modular-buildroot feature (which this patch is a part of...) and we then push a metadata-only change to the modulemd that marks the nodejs:10 module as the default for Fedora 30, which takes over the update path from the non-modular RPM. If we require that the metadata must have a matching module stream, then it necessitates either rebuilding that module stream for the `fedora-updates` repo or else copying the data from the frozen `fedora` repo into the `fedora-updates` repo, wasting a lot of space. I'd much rather that we just always pass modulemd-defaults documents as-is. I think it's going to be pretty rare that this matters, but if we need to make a change like this and an overzealous filter gets in the way, it'll be difficult to track down and quite annoying.
> 
> Case 5 (translations), I think is even _more_ likely to hit this than defaults, since new translations could arrive in the compose at any time, whereas defaults changes will be likely less common. We're working on automation to have pungi pull the latest translations from Zanata on each nightly compose and add the metadata to the modulemd document. If createrepo_c then chucks it back out, it will make that function largely useless.

**Comment by sgallagher** [comment]
Further from @Conan-Kudo :
> > Maybe we should just agree this is a hard failure for the createrepo operation and that if we end up with only a partial match, we assume that the repo was not properly populated. Reasonable?
> 
> That makes sense to me.
> 
> > For cases 4 and 5, I tried to explain in the original comment, but my view is that these are valid cases that we cannot reasonably be able to detect, short of duplicating data unnecessarily. It is completely reasonable that we might ship nodejs:10 as a module in Fedora 30's frozen fedora repository. Then, later in F30's life, we complete the default-modules-in-the-non-modular-buildroot feature (which this patch is a part of...) and we then push a metadata-only change to the modulemd that marks the nodejs:10 module as the default for Fedora 30, which takes over the update path from the non-modular RPM. If we require that the metadata must have a matching module stream, then it necessitates either rebuilding that module stream for the fedora-updates repo or else copying the data from the frozen fedora repo into the fedora-updates repo, wasting a lot of space. I'd much rather that we just always pass modulemd-defaults documents as-is. I think it's going to be pretty rare that this matters, but if we need to make a change like this and an overzealous filter gets in the way, it'll be difficult to track down and quite annoying.
> 
> Ugh, I see your point...
> 
> > Case 5 (translations), I think is even more likely to hit this than defaults, since new translations could arrive in the compose at any time, whereas defaults changes will be likely less common. We're working on automation to have pungi pull the latest translations from Zanata on each nightly compose and add the metadata to the modulemd document. If createrepo_c then chucks it back out, it will make that function largely useless.
> 
> I don't think translations for things that don't have any content associated with them would matter that much...

I think you misunderstand. These aren't translations for things with no associated content. They're translations for things that are in another repository. Similar to the defaults example I gave, they are updated translations for content that exists only in the frozen `fedora` repository.

**Comment by Conan-Kudo** [comment]
> I think you misunderstand. These aren't translations for things with no associated content. They're translations for things that are in another repository. Similar to the defaults example I gave, they are updated translations for content that exists only in the frozen fedora repository.

That doesn't make sense. Why aren't the translations associated with the repository the content is from?

**Comment by sgallagher** [comment]
> > I think you misunderstand. These aren't translations for things with no associated content. They're translations for things that are in another repository. Similar to the defaults example I gave, they are updated translations for content that exists only in the frozen fedora repository.
> 
> That doesn't make sense. Why aren't the translations associated with the repository the content is from?

Because in some cases that repository can no longer be updated. The classic example is the `fedora` repository. Once Fedora is released, that repository cannot be modified. All changes have to go through `updates-testing` and `updates`. So our choices become: "Translations cannot be updated or added for a new language except when a module update occurs" or "Allow translations to be distinct from the content in the repository".
