### ISSUE TITLE
mergerepos_c doesn't support --koji `simple` mode

### ISSUE THREAD

**Issue by tkopecek** [rpm-software-management/createrepo_c#137]
We've introduced [new behaviour](https://pagure.io/koji/pull-request/1066) in koji's variant of mergerepo some time ago. This was needed to support some distributions which doesn't have "correct" repos (mixing rpms from different versions of origin srpm). It would be nice to have compatible implementation in mergerepo_c, so users can once again use faster implementation.

**Comment by Conan-Kudo** [comment]
For reference, the new mergerepos changes:
* https://pagure.io/koji/c/a2c61d39924e6768474916837ee91de66b889022
* https://pagure.io/koji/c/9effd55c397b4a1abda33cf0a654ec01a0011b99

**Comment by kontura** [comment]
I created a PR #139 for this, but I am not sure if it covers all the desired behavior.

**Comment by Conan-Kudo** [comment]
This is now supported in v0.13.0.
