### ISSUE TITLE
--keep-all-metadata missing from createrepo_c manual page

### ISSUE THREAD

**Issue by kenyon** [rpm-software-management/createrepo_c#138]
The --keep-all-metadata option is missing from the createrepo_c manual page.

**Comment by kontura** [comment]
I think it should be in there. 
Isn't this it: https://github.com/rpm-software-management/createrepo_c/blob/master/doc/createrepo_c.8#L152?

**Comment by kenyon** [comment]
Ah yeah I missed it because of the slashes, and I think my older version didn't have the option.
