### ISSUE TITLE
createrepo_c failed to include some rpms, reported "Value too large for defined data type" reading files

### ISSUE THREAD

**Issue by ferdnyc** [rpm-software-management/createrepo_c#140]
We hit an issue recently in rpmfusion's koji with the newRepo() task, which uses createrepo_c to incorporate newly-built packages tagged for buildroot override into the new buildroot set.

After successfully building libopenshot-audio for both [f29](http://koji.rpmfusion.org/koji/taskinfo?taskID=308757) and [f28](http://koji.rpmfusion.org/koji/taskinfo?taskID=308759), I tagged the packages for buildroot override, which automatically fires off newRepo() tasks ([f29](http://koji.rpmfusion.org/koji/taskinfo?taskID=308781), [f28](http://koji.rpmfusion.org/koji/taskinfo?taskID=308786)) to regenerate the buildroot sets. These tasks each run a `createrepo_c` subtask for each supported architecture, pulling in the newly-tagged packages (in this case, `libopenshot-audio-0.1.8-1.fc29` and `...fc28`).

However, in this particular case, two of the `createrepo_c` tasks did not correctly include the new packages from those builds. In both [armhfp on f29](http://koji.rpmfusion.org/koji/taskinfo?taskID=308796) and [aarch64 on f28](http://koji.rpmfusion.org/koji/taskinfo?taskID=308805), while the tasks reported a successful result (something that may be related to #129 ?), the last line of each tasks's createrepo.log reads "Pool finished with errors", and the log output when reading the new rpm files contains failure messages.

Here's an abbreviated example from f28's aarch64 [createrepo.log](http://koji.rpmfusion.org/kojifiles/work/tasks/8805/308805/createrepo.log), the [createrepo.log](http://koji.rpmfusion.org/kojifiles/work/tasks/8796/308796/createrepo.log) for armhfp on f29 is virtually identical. 

(Long lines have been wrapped for readability.)
```
$ /usr/bin/createrepo_c -vd -o /var/tmp/koji/tasks/8805/308805/repo -i /mnt/koji/repos/f28-free-
build/44477/aarch64/pkglist -g /mnt/koji/repos/f28-free-build/44477/groups/comps.xml --update
--skip-stat /mnt/koji/repos/f28-free-build/44477/aarch64
05:40:28: Version: 0.12.1 (Features: DeltaRPM LegacyWeakdeps )
05:40:28: Signal handler setup
05:40:28: Thread pool ready
05:40:28: Skipping dir walk - using pkglist
05:40:28: Adding pkg: /mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/
terminatorX/4.0.1/4.fc28/aarch64/terminatorX-4.0.1-4.fc28.aarch64.rpm
05:40:28: Adding pkg: /mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/
vdr-weatherforecast/0.2.0/4.fc28/aarch64/vdr-weatherforecast-0.2.0-4.fc28.aarch64.rpm

[...]

05:40:28: Adding pkg: /mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/
VirtualBox/6.0.4/2.fc28/noarch/VirtualBox-kmodsrc-6.0.4-2.fc28.noarch.rpm
05:40:28: Adding pkg: /mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/
libopenshot-audio/0.1.8/1.fc28/aarch64/libopenshot-audio-devel-0.1.8-1.fc28.aarch64.rpm
05:40:28: Adding pkg: /mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/
libopenshot-audio/0.1.8/1.fc28/aarch64/libopenshot-audio-0.1.8-1.fc28.aarch64.rpm
05:40:28: Package count: 422
05:41:05: cr_metadata_load_xml: Parsed items: 420
05:41:05: cr_metadata_load_xml: Really usable items: 420
05:41:05: Old metadata from: /var/tmp/koji/tasks/8805/308805/repo/ - loaded
05:41:05: Copy groupfile /mnt/koji/repos/f28-free-build/44477/groups/comps.xml ->
/var/tmp/koji/tasks/8805/308805/repo/.repodata/comps.xml
05:41:05: Creating .xml.gz files
05:41:05: Setting number of packages
05:41:05: Creating databases
05:41:05: Thread pool user data ready
05:41:05: CACHE HIT BasiliskII-1.0-0.20171001.7.fc28.1.aarch64.rpm

[...]

05:41:06: CACHE HIT lives-2.10.2-1.fc28.aarch64.rpm
05:41:06: CACHE HIT ltris-1.0.19-4.fc28.aarch64.rpm
C_CREATEREPOLIB: Warning: load_rpm: stat(/mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-0.1.8-1.fc28.aarch64.rpm) error (Value too large for defined data type)
C_CREATEREPOLIB: Warning: Cannot read package: /mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-0.1.8-1.fc28.aarch64.rpm: stat(/mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-0.1.8-1.fc28.aarch64.rpm) failed: Value too large for defined data type
05:41:06: CACHE HIT m2vrequantiser-20030929-10.fc28.aarch64.rpm
C_CREATEREPOLIB: Warning: load_rpm: stat(/mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-devel-0.1.8-1.fc28.aarch64.rpm) error (Value too large for defined data type)
C_CREATEREPOLIB: Warning: Cannot read package: /mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-devel-0.1.8-1.fc28.aarch64.rpm: stat(/mnt/koji/repos/f28-free-build/
44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/
libopenshot-audio-devel-0.1.8-1.fc28.aarch64.rpm) failed: Value too large for defined data type
05:41:06: CACHE HIT mamory-0.2.25-14.fc28.aarch64.rpm
05:41:06: CACHE HIT mamory-devel-0.2.25-14.fc28.aarch64.rpm

[...]

05:41:06: CACHE HIT zoneminder-nginx-1.32.3-1.fc28.aarch64.rpm
05:41:07: Generating repomd.xml
05:41:08: posix_spawn avoided (fd close requested) 
05:41:08: posix_spawn avoided (fd close requested) 
05:41:08: posix_spawn avoided (fd close requested) 
05:41:08: Copying files from old repository to the new one
05:41:08: Retention type: 0 (0)

[...]

05:41:08: posix_spawn avoided (fd close requested) 
05:41:08: Old repo /var/tmp/koji/tasks/8805/308805/repo/repodata.old.32711.20190323054108.772350 removed
05:41:08: Memory cleanup
05:41:08: All done
Directory walk done - 422 packages
Loaded information about 420 packages
Temporary output repo path: /var/tmp/koji/tasks/8805/308805/repo/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
Pool finished with errors
```

As you can see, the initial pass through the packages reported no issues, but the "Creating databases" pass reported failures from `load_rpm`, with the error message "Value too large for defined data type". The new packages were therefore not included in the buildroot, and [a subsequent attempt](http://koji.rpmfusion.org/koji/taskinfo?taskID=308810) to build libopenshot (which depends on libopenshot-audio) therefore failed on the architectures which exhibited this issue.

As one final wrinkle, when _later_ `newRepo()` tasks were triggered for [f29](http://koji.rpmfusion.org/koji/taskinfo?taskID=308920) and [f28](
http://koji.rpmfusion.org/koji/taskinfo?taskID=309020), the `createrepo_c` subtasks completed without incident for all architectures, including the previous failures, finally incorporating `libopenshot-audio-0.1.8-1` and resolving the dependency issue.

Any insights you can offer into the source of the "Value too large for defined data type" error message or the nature of this (apparently transient) failure would be helpful and most appreciated.

CC: @kwizart

**Comment by kontura** [comment]
The problem comes from the calls of:
[stat](http://man7.org/linux/man-pages/man2/stat.2.html)(/mnt/koji/repos/f28-free-build/44477/aarch64/toplink/packages/libopenshot-audio/0.1.8/1.fc28/aarch64/libopenshot-audio-0.1.8-1.fc28.aarch64.rpm)

I was able to find [this](https://www.gnu.org/software/coreutils/faq/coreutils-faq.html#Value-too-large-for-defined-data-type) regarding the error message.

From what I understand it's possible you don't have the necessary utilities compiled with large file support enabled on aarch64 and armhfp. However I don't think libopenshot-audio-0.1.8-1.fc28.aarch64.rpm could be over 2GB in size, so that is confusing.

**Comment by ferdnyc** [comment]
@kontura Thanks for the info, and that FAQ pointer.

As you say, `libopenshot-audio.rpm` can't possibly have been > 2GB (it's 1.6MB on `x86_64`), and anyway `/usr/bin/createrepo_c` on any of our koji buildhosts would come from the official distro packages, which I can't imagine would be built without large file support.

There's also the fact that the operation succeeded the next time that task was run. ...It's perplexing.

**Comment by kontura** [comment]
I am closing this issue since there is nothing we can do about it right now.

If this occurs again or there is some new relevant information about this please don't hesitate to reopen the issue.
