### ISSUE TITLE
createrepo_c print normal output to STDERR

### ISSUE THREAD

**Issue by xsuchy** [rpm-software-management/createrepo_c#149]
createrepo_c prints to STDERR which confuse mockchain https://github.com/rpm-software-management/mock/issues/249
I will address this in mockchain, but printing normal output to STDERR is definitely wrong.
It problem as in past and even now there are issues with correct return code. E.g., https://github.com/rpm-software-management/createrepo_c/issues/129

**Comment by xsuchy** [comment]
Ping. Any progress on this?

**Comment by kontura** [comment]
I think this should be fixed by https://github.com/rpm-software-management/createrepo_c/pull/141.

**Comment by xsuchy** [comment]
So this should be fixed in Release 0.13.0. Hmmm, checking versions... Fedoras OK. RHEL 8.1 has 0.11 which does not have this issue and 8.2 will have 0.15. RHEL 7 has createrepo_c-0.12.2-2.el7. That is in EPEL, which should be easy for an update. Would you be willing to do backport to EL7?

**Comment by kontura** [comment]
Sorry I missed this response. I am willing to do the backport to EL7 but I am afraid I won't get to it until the new year.

**Comment by dralley** [comment]
Can this issue be closed then?  If it's fixed.
