### ISSUE TITLE
RFE: rewrite createrepo_c to use libxml2 only

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/createrepo_c#150]
For some reasons createrepo_c uses two xml parsers and it is not possible to not use one of them
I think that it will be good to rewrite it to use only libxml2 to minimise dependencies.

**Comment by kontura** [comment]
Can you be a bit more specific what exactly do you mean by two xml parsers? When it comes to xml dependencies I have only been able to find libxml2, even in the spec file there is only [this](https://github.com/rpm-software-management/createrepo_c/blob/4570d46b7837d0dbdb7b5f9ffb1e77ea7068c316/createrepo_c.spec#L44).

Or is there some other xml dependency I am missing?

**Comment by kloczek** [comment]
createrepo_c uses expat and libxml2 which are libraries proving parser and some additional set of operation s on xml objects/files.

**Comment by kontura** [comment]
oh I see, you are right.
One more thing I have looked into the commit log where the Expat library was introduced and it seems like it was [deliberately put there to replace libxml2](https://github.com/rpm-software-management/createrepo_c/commit/4c5c0c0b71f588c9303d3d41df6d0687cd06535e) when parsing xml. 

I can't find any specific reason why it was done, but even though it would be better to have just one I think we should first test whether it wasn't for example much slower or something like that.

**Comment by kloczek** [comment]
In the patch there is no any traces about causes of such switch.
Something is wrong with libxml2 locate_and_load_xml_metadata_2()?

**Comment by kloczek** [comment]
AFAIK libxml2 was generally faster than expat.
Memory consumption was as same smaller and this is why generally almost everywhere is used libxml2 and only in few cases expat.

**Comment by kloczek** [comment]
https://cpp.libhunt.com/compare-expat-vs-libxml2

**Comment by tpgxyz** [comment]
```
[tpg@tpg-virtualbox createrepo_c-0.14.0]$ grep -ri libxml | wc -l
33
```
Looks like xml_dump*.{c,h} and repomd.c still requires libxml2

**Comment by kloczek** [comment]
Is it any problem with libxml2 that createrepo_c seems is trying to move away from that library and use expat? (which is now less and less used)

**Comment by Conan-Kudo** [comment]
Unfortunately, I don't know why we were moving to expat, as generally we've been moving to libxml2 in recent years. That was something @Tojaj was doing back then.

I'd probably say we should switch back to libxml2 completely (as we've done for libsolv and other libraries that used expat).

**Comment by jailbird777** [comment]
I totally +1 this, as the libexpat loading of the previous data when using --update is horrible slow once your dataset gets into the multi-megabyte size.  filelists.xml easily gets this big.

**Comment by Conan-Kudo** [comment]
This is done with 0.15.8 release.
