### ISSUE TITLE
0.13.0: test suite is failing

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/createrepo_c#157]
<pre>2: test_xml_parser_repomd_repo01_nowarningcb (tests.test_xml_parser.TestCaseXmlParserRepomd) ... ok
2: 
2: ======================================================================
2: ERROR: test_metadatalocation (tests.test_locate_metadata.TestCaseMetadataLocation)
2: ----------------------------------------------------------------------
2: Traceback (most recent call last):
2:   File &quot;/home/tkloczko/rpmbuild/BUILD/createrepo_c-0.13.0/tests/python/tests/test_locate_metadata.py&quot;, line 28, in test_metadatalocation
2:     ml = cr.MetadataLocation(REPO_WITH_ADDITIONAL_METADATA, 0)
2: createrepo_c.CreaterepoCError: Module metadata found in repository, but createrepo_c was not compiled with libmodulemd support.
2: 
2: ----------------------------------------------------------------------
2: Ran 97 tests in 0.151s
2: 
2: FAILED (errors=1)
2/2 Test #2: test_python ......................***Failed    0.74 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.75 sec

The following tests FAILED:
	  2 - test_python (Failed)
Errors while running CTest
</pre>

**Comment by kontura** [comment]
Yes we already had an issue for this #153 and it should be fixed now. :+1:

**Comment by Conan-Kudo** [comment]
This has been fixed since 0.13.1
