### ISSUE TITLE
Fix null pointer crash in cr_dumper_thread() if it fails to  get checksum

### ISSUE THREAD

**Issue by gauravgup1** [rpm-software-management/createrepo_c#176]
If the call to cr_checksum_file() inside get_checksum() fails, tmp_err
is propagated to err and makes it back to the caller load_rpm(). But
load_rpm() doesn't propagate the error back to its caller
cr_dumper_thread(). As a result when cr_dumper_thread() tries to print a
warning, it crashes with a null pointer exception on tmp_err.

Attaching a fix for the problem.

[0001-Fix-null-pointer-crash-in-cr_dumper_thread-if-it-fai.txt](https://github.com/rpm-software-management/createrepo_c/files/3547493/0001-Fix-null-pointer-crash-in-cr_dumper_thread-if-it-fai.txt)

**Comment by Conan-Kudo** [comment]
Committed as 4f0d10c9f1e4301ee513096c827fb725b8cb7f1a.

Thanks for the patch, but please send a pull request in the future. It's much harder for me to notice there are fixes when they are submitted as attachments to issues...

**Comment by gauravgup1** [comment]
Will do in the future, thanks.
