### ISSUE TITLE
0.15.3: intrruped indexing does not removes .repodata/ directory

### ISSUE THREAD

**Issue by kloczek** [rpm-software-management/createrepo_c#188]
<pre>tkloczko@barrel]$ ls -ld SRPMS/{repodata,.repodata}
ls: cannot access &apos;SRPMS/.repodata&apos;: No such file or directory
drwxrwxr-x. 1 tkloczko tkloczko 986 Dec  3 00:14 <font color="#0087FF">SRPMS/repodata</font>

[tkloczko@barrel]$ createrepo_c SRPMS 
Directory walk started
Directory walk done - 905 packages
Temporary output repo path: SRPMS/.repodata/
Preparing sqlite DBs
Pool started (with 5 workers)
^CInterrupt catched: Terminating...

[tkloczko@barrel]$ ls -ld SRPMS/{repodata,.repodata}
drwxrwxr-x. 1 tkloczko tkloczko 168 Dec  3 18:04 <font color="#0087FF">SRPMS/.repodata</font>
drwxrwxr-x. 1 tkloczko tkloczko 986 Dec  3 00:14 <font color="#0087FF">SRPMS/repodata</font>
</pre>

**Comment by Conan-Kudo** [comment]
Fixed with release of 0.15.6
