### ISSUE TITLE
Remove Python 2 specific code / build steps

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/createrepo_c#195]
Python 2 is now officially EOL so (eventually) upstream support can be removed, although, I do not know if support cycles make this unlikely to happen soon.

**Comment by Conan-Kudo** [comment]
I'm planning on doing this for 0.16.0.

**Comment by dralley** [comment]
Guess not?

**Comment by Conan-Kudo** [comment]
@dralley Unfortunately with merging a behavior change, I decided to bump before recalling I wanted to do this too... This is why I shouldn't do these things late at night...

**Comment by Conan-Kudo** [comment]
I'll probably make a PR to drop it this week and if nobody screams in a week or so, then I'll merge it and bump to 0.17.0.

**Comment by dralley** [comment]
@Conan-Kudo Take a look at https://github.com/rpm-software-management/createrepo_c/pull/240 when you get a chance
