### ISSUE TITLE
urlencode `+` symbol in links to RPMs?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/createrepo_c#215]
Hi, when some RPM repository is synced to AWS s3 mirror, URLs pointing to
RPMs with `+` symbol inside (there are less-important other symbols, see [1])
can not be downloaded without url-encoding.  See the difference:

```
$ wget 'https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/31/Everything/x86_64/Packages/l/libstdc++-9.3.1-1.fc31.x86_64.rpm'
--2020-04-07 05:36:11--  https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/31/Everything/x86_64/Packages/l/libstdc++-9.3.1-1.fc31.x86_64.rpm
Resolving d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)... 13.32.118.75, 13.32.118.232, 13.32.118.221, ...
Connecting to d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)|13.32.118.75|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-04-07 05:36:11 ERROR 404: Not Found.

$ wget 'https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/31/Everything/x86_64/Packages/l/libstdc%2B%2B-9.3.1-1.fc31.x86_64.rpm'
--2020-04-07 05:36:14--  https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/31/Everything/x86_64/Packages/l/libstdc%2B%2B-9.3.1-1.fc31.x86_64.rpm
Resolving d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)... 13.32.118.232, 13.32.118.221, 13.32.118.26, ...
Connecting to d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)|13.32.118.232|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 648195 (633K) [binary/octet-stream]
Saving to: ‘libstdc++-9.3.1-1.fc31.x86_64.rpm’

libstdc++-9.3.1-1.fc31.x86_64.rpm                           100%[========================================================================================================================================>] 633.00K  --.-KB/s    in 0.1s    

2020-04-07 05:36:14 (5.36 MB/s) - ‘libstdc++-9.3.1-1.fc31.x86_64.rpm’ saved [648195/648195]
```

Would it be possible to url-encode those symbols in RPM locations?  The `+` symbol
is at least in `c++`, stuff like `gtk+`...:

```
cat 87aea7fb189357f558fad367a3882383cb8804a6e666b2ad655b4321a75069f7-primary.xml | grep \<location | grep '+' | wc -l
247
```
I was afraid of `~` symbol, per our versioning guidelines [2] (it will be more frequent
in future) and that AWS claims we shouldn't use that at all - but it seems to work fine.

[1] Characters That Might Require Special Handling
    https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys
[2] https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_versioning_prereleases_with_tilde

**Comment by praiskup** [comment]
Perhaps we can calmly url-encode the `location=` field without special-casing
plus symbol, I don't know.  The only symbol that causes problems seems to
be `+` ATM.

Report per discussion in https://pagure.io/fedora-infrastructure/issue/8679

**Comment by kontura** [comment]
We have a [bug](https://bugzilla.redhat.com/show_bug.cgi?id=1817130) dealing with something very similar on DNF side. I have asked @lukash about it and it seems that url-encoding all the data in `<location>` element could result in DNF saving the packages locally under the url-encoded names which I think we don't want. I might yet test it to see what happens if we did the encoding, at least with dnf.

But could possibly fixing the bug fix your problem as well? Or are you not using dnf to do the downloads?

**Comment by lukash** [comment]
This really is the same bug, unless I'm missing something. IMO the URL should only be encoded for the download, I've got a fix already, just working on a test case for it.

**Comment by lukash** [comment]
PRs with a fix for dnf and a test:
https://github.com/rpm-software-management/librepo/pull/188
https://github.com/rpm-software-management/ci-dnf-stack/pull/819

If you encoded the `<location>` element, it would likely break anything that is reading it and not using it strictly for constructing the download URL. I'm quite sure any tool composing an URL from the location needs to escape it itself.

@kontura I'll leave this for you to close :slightly_smiling_face:

**Comment by praiskup** [comment]
I considered filing this against dnf first, but that seemed like invalid
choice to me considering that (a) metadata are generated correctly, and
(b) AWS is not mis-behaving.

> If you encoded the <location> element, it would likely break anything
> that is reading it and not using it strictly for constructing the
> download URL.

I understand the backward-compat worries.  Do you have some practical
examples of tools which are doing this?

I mean, if we url-encoded this in metadata directly, no single reader
would have to special-handle the `+` sign in metadata.  And it sounds
completely valid to expect that `href=` in `<location href="...">` can be
URL encoded.

**Comment by lukash** [comment]
> I understand the backward-compat worries. Do you have some practical
> examples of tools which are doing this?

No, but I have very little awareness of the ecosystem... I'm only guessing, but I'm quite certain there's gonna be something somewhere.

> I mean, if we url-encoded this in metadata directly, no single reader
> would have to special-handle the `+` sign in metadata. And it sounds
> completely valid to expect that `href=` in `<location href="...">` can be
> URL encoded.

Not really. Composing an URL from the `<location>` tag is only one use of the value. The path is also used on local filesystem for naming the file when saving and for copying the file locally. You'd need to go through the trouble of decoding for that. And for a transition period we'd actually have a problem knowing if the metadata file you have has the `<location>`s encoded or not - we'd need to version the data basically.

The tag itself in no way indicates the value is an URL, it just used to compose one, sometimes, and it's during the URL composition when you should encode it. It's (IMO) the correct way to do it in addition to it not breaking the compatibility of the metadata.

**Comment by praiskup** [comment]
> Not really. Composing an URL from the <location> tag is only one use of the
> value. The path is also used on local filesystem for naming the file when
> saving and for copying the file locally.

But we use curl since ever, and it seems to work just fine:
```
$ curl file:///tmp/+
ahoj
$ curl file:///tmp/%2B
ahoj
```
> You'd need to go through the trouble of decoding for that. 

Now you have to anyways, but from the other way around - you need to encode
it.  And every other metadata reader will have to.

> The tag itself in no way indicates the value is an URL,

When I see `href=` [I see this](https://html.spec.whatwg.org/dev/semantics.html#attr-link-href)

**Comment by praiskup** [comment]
Now I realized that I don't have any motivation to fix this, because fedora
[started to do different AWS i3 mirroring mechanism](https://pagure.io/fedora-infrastructure/issue/8679)
which doesn't suffer from the `+` problem (as I now realized, because I noticed
that Copr repositories aren't either affected).  E.g. try this:

```
$ wget https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/testing/32/Everything/x86_64/Packages/g/gcc-c++-10.0.1-0.11.fc32.x86_64.rpm
--2020-04-17 13:58:25--  https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/testing/32/Everything/x86_64/Packages/g/gcc-c++-10.0.1-0.11.fc32.x86_64.rpm
Resolving d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)... 13.32.118.231, 13.32.118.61, 13.32.118.232, ...
Connecting to d2lzkl7pfhq30w.cloudfront.net (d2lzkl7pfhq30w.cloudfront.net)|13.32.118.231|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11692735 (11M) [application/x-rpm]
Saving to: ‘gcc-c++-10.0.1-0.11.fc32.x86_64.rpm’

gcc-c++-10.0.1-0.11.fc32.x86_64.rpm                         100%[========================================================================================================================================>]  11.15M  6.64MB/s    in 1.7s    

2020-04-17 13:58:27 (6.64 MB/s) - ‘gcc-c++-10.0.1-0.11.fc32.x86_64.rpm’ saved [11692735/11692735]
```

As long as Fedora/Copr goes, we are fine to close this.  CentOS guys should
follow the same pattern as Fedora does, and it should be fine.

**Comment by lukash** [comment]
> > Not really. Composing an URL from the  tag is only one use of the
> > value. The path is also used on local filesystem for naming the file when
> > saving and for copying the file locally.
> 
> But we use curl since ever, and it seems to work just fine:
> 
> ```
> $ curl file:///tmp/+
> ahoj
> $ curl file:///tmp/%2B
> ahoj
> ```

The `curl` binary does that with URLs... not sure where you use `curl` and I'm not sure if the `curl` C API somehow does this automatically too, I doubt it but didn't check. It makes sense the `curl` binary does this... but it seem quite besides the point here.

> > You'd need to go through the trouble of decoding for that.
> 
> Now you have to anyways, but from the other way around - you need to encode
> it. And every other metadata reader will have to.

Yes, but only if using it as an URL for actually downloading the file. If it uses it for e.g. looking up the file in a local repository, it doesn't do it, and that is good.

> > The tag itself in no way indicates the value is an URL,
> 
> When I see `href=` [I see this](https://html.spec.whatwg.org/dev/semantics.html#attr-link-href)

But it is not a `href`, which requires a whole URL, note the difference... here (unless I'm very much mistaken?) we only have e.g. `<location>Packages/l/librepo-1.0.0-1.fc31.x86_64.rpm</location>`. That is not an URL (or URI if you want to distinguish).

> Now I realized that I don't have any motivation to fix this, because fedora ...

What was your motivation though? The fix I posted for dnf would fix it for you as well?

> ... [started to do different AWS i3 mirroring mechanism](https://pagure.io/fedora-infrastructure/issue/8679)
> which doesn't suffer from the `+` problem (as I now realized, because I noticed
> that Copr repositories aren't either affected). E.g. try this:
> ...

Well, the thing here is, that the `+` sign doesn't have a special meaning in the _path_ part of an URI. And the specification, to my very brief skim-through, kind of says that and doesn't therefore mandate encoding of `+` in the _path_ part. It can certainly work. Depends on the server implementation. Probably the only characters that need to be encoded are `?`, `#` and utf-8? Neither is allowed in a package name.

So perhaps we should be telling people to fix their servers? But I think we should still be encoding the path.

> As long as Fedora/Copr goes, we are fine to close this. CentOS guys should
> follow the same pattern as Fedora does, and it should be fine.

Again, I'm fixing this for dnf. If there are other places, perhaps they should still be considered, as people can still run into incompatible servers otherwise.

**Comment by praiskup** [comment]
> But it is not a href, which requires a whole URL

I've seen relative `href`s as well, but that might be against some RFE, I'm lazy
to check now.

> What was your motivation though? The fix I posted for dnf would fix it for you as well?

I thought that copr/fedora repos are broken, but they are not (fedora quite freshly).

IOW, nothing necessarily needs fixes.  Neither DNF.

**Comment by praiskup** [comment]
> Again, I'm fixing this for dnf. If there are other places, perhaps they should
> still be considered, as people can still run into incompatible servers
> otherwise.

Unless I'm mistaken, the issues with `+` sign are almost always caused by
wrongly synced AWS I3 mirror - while there's actually no need to sync any
mirror; i3 is able to work as transparent proxy which doesn't suffer from
this problem.

> So perhaps we should be telling people to fix their servers?

Yes, I think so.

**Comment by lukash** [comment]
Ok, I'll close this. FWIW I did check "+" is not a reserved character in URL so not necessary to encode, but we'll put the encoding in place anyway, to make dnf more compatible.

**Comment by praiskup** [comment]
> to make dnf more compatible.

My advice would be to not even do this, and rather document that  people shouldn't
do the I3 mirrors wrongly.  It's not just about that, the normal `aws i3 sync` is
**extremely** hard task to do right... (and we eventually gave up iterating in Fedora).

Sounds like wasting of efforts.

**Comment by praiskup** [comment]
Ah I see, the report against librepo is probably triggered by something else
than wrongly done i3 mirror ... and it is regression from urlgrabber.  So let's
scratch my advice.
