### ISSUE TITLE
request for release with the large XML body fix

### ISSUE THREAD

**Issue by evgeni** [rpm-software-management/createrepo_c#229]
Hey,

I am not sure this is the best way to ask for a fresh `createrepo_c` release, but I'll try ;-)

Would it be possible to get a 0.16.1 released with the fixes from #225? Looking at the git history since 0.16.0 it should be safe to just release what's in the main branch currently?

Thanks in advance
Evgeni

**Comment by kontura** [comment]
I made the release. :slightly_smiling_face:
