### ISSUE TITLE
test_cr_detect_compression_bad_suffix failing on Alpine Linux

### ISSUE THREAD

**Issue by Cogitri** [rpm-software-management/createrepo_c#258]
Hello,

the mentioned test fails on Alpine:

```
ERROR:/var/home/rasmus/Projects/aports/testing/createrepo_c/src/createrepo_c-0.17.1/tests/test_compression_wrapper.c:219:test_cr_detect_compression_bad_suffix: assertion failed (ret == CR_CW_XZ_COMPRESSION): (1 == 5)
```

Tested with 0.17.1

**Comment by kontura** [comment]
Hello,
can you share more details? All the c tests (including the one you mentioned) work for me. I did:
```
podman run -it docker.io/library/alpine
apk --update add bzip2-dev cmake expat-dev file-dev glib-dev curl-dev libxml2-dev python3-dev rpm-dev openssl-dev sqlite-dev xz-dev zlib-dev musl-dev make gcc
wget https://github.com/rpm-software-management/createrepo_c/archive/refs/tags/0.17.1.zip
unzip 0.17.1.zip
cd createrepo_c-0.17.1/
mkdir build && cd build
cmake .. -DWITH_ZCHUNK=0 -DWITH_LIBMODULEMD=0
make && make tests && cd ..
/bin/sh ./build/tests/run_gtester.sh
```

But I do get 2 fails running the python tests:
```
WITH_LIBMODULEMD=OFF PYTHONPATH=`readlink -f ./build/src/python/` python3 -m unittest discover -bs tests/python/
```
These are cause by incompatible `unxz` binary, we use `--stdout` switch but in my alpine container it supports only the short `-c`, we could fix this.

**Comment by Cogitri** [comment]
Hej,

sorry for the late reply, somehow I missed the email notification for your reply :/

The following Dockerfile reproduces the failure for me:

```
FROM alpine:edge
RUN apk add 	bash-completion bzip2-dev cmake curl-dev expat-dev file-dev glib-dev openssl-dev libxml2-dev  python3-dev rpm-dev scanelf sqlite-dev xz-dev zlib-dev alpine-sdk check-dev py3-nose xz
RUN wget https://github.com/rpm-software-management/createrepo_c/archive/refs/tags/0.17.1.zip
RUN unzip 0.17.1.zip
RUN cd createrepo_c-0.17.1 && mkdir build && cd build \
    && cmake .. -DWITH_ZCHUNK=0 -DWITH_LIBMODULEMD=0 \
    && make && make tests && cd .. \
    && /bin/sh ./build/tests/run_gtester.sh
``

**Comment by kontura** [comment]
It looks like the `edge` repository has newer `file-dev` and `libmagic`. It has `file-dev-5.40-r0` and `libmagic-5.40-r0` which break the test whereas it works with `libmagic-5.39-r0` (these are present in my container).

On fedora I have `file-devel-5.40-6.fc35.x86_64` and it works, looking at the [fedora package sources](https://src.fedoraproject.org/rpms/file/tree/rawhide) there are a couple of patches dealing with magic and even on xz specific (`file-5.40-magic-xzip.patch`, which is upstream commit `9b0459afab309a82aa4e46f73a4e50dd641f3d39`), maybe this fixes the issue?

**Comment by Cogitri** [comment]
Ah yes, seems like those patches to file fix it, thanks for the help! :)
