### ISSUE TITLE
automatically include compressed module metadata

### ISSUE THREAD

**Issue by carlwgeorge** [rpm-software-management/createrepo_c#263]
createrepo_c automatically includes `*modules.yaml` files it detects.  It does not automatically include the compressed equivalent, i.e. `*modules.yaml.gz`.  Please update createrepo_c to automatically include compressed module metadata.

**Comment by kontura** [comment]
Can you explain in a bit more detail what is the use case?
I mean is it important that the exact `*modules.yaml.gz` is simply added to the repodata or would it be fine to find the file, decompress it, possibly merge it with any other modular metadata found and then compress it all into a single `modules.yaml.gz`?

**Comment by carlwgeorge** [comment]
> find the file, decompress it, possibly merge it with any other modular metadata found and then compress it all into a single modules.yaml.gz

This is precisely what I'm looking for.

To be more clear, here is my use case.  I would like to merge a new modular repo (repo2) into an existing modular repo (repo1).  I'm doing that by rsyncing repo2 over the top of repo1, and running `createrepo_c --update --retain-old-md-by-age 1m .`  When this command is run the repodata directory has two `*-modules.yaml.gz` files in it, and they are **not** merged and not included in the final repodata.  If I manually gunzip them prior to running createrepo_c, they are merged into a new `*-modules.yaml.gz` file.

**Comment by kontura** [comment]
I see, yes I think we could add that. 

Just one more thing have you considered `mergerepo_c`? It could do what you need and you might even be able to pass the url to the repo2 directly and skip the rsync step. Although it handles only the repodata not packages.

**Comment by carlwgeorge** [comment]
I considered it, but I don't see the benefit if I still have to rsync over the packages separately.

**Comment by Conan-Kudo** [comment]
It would be nice if `mergerepo_c` could optionally actually merge the package sets together too, but I think this RFE is valid regardless.

**Comment by kontura** [comment]
I have been slowly working on this, here is a PR: https://github.com/rpm-software-management/createrepo_c/pull/268

**Comment by kontura** [comment]
There are some problems with the current implementation so here is a follow up patch: https://github.com/rpm-software-management/createrepo_c/pull/276

I also wanted to point out that to achieve the desired behavior its necessary to use `--keep-all-metadata` otherwise the `modules.yaml` from repo1 (the original repo) is not merged, this option kind of complements `--retain-old-md*` options which work only for the main metadata (primary, filelists, other). 

The final command could look like: `createrepo_c --update --keep-all-metadata --retain-old-md-by-age 1m .`
