### ISSUE TITLE
createrepo_c fails in Docker container with Invalid cross-device link error

### ISSUE THREAD

**Issue by tewarid** [rpm-software-management/createrepo_c#266]
The following g_rename [fails to work in Docker containers](https://github.com/moby/moby/issues/25409) that use the overlay2 storage driver (the default), when the source directory is in a read-only layer

https://github.com/rpm-software-management/createrepo_c/blob/410ae77383086a3b599eb98399eb5c66abd95fc9/src/createrepo_c.c#L2024-L2030

This can be observed with debug logging enabled

```text
Old repodata doesn't exists: Cannot rename xxx -> yyy: Invalid cross-device link
```

**Comment by kontura** [comment]
I believe this should be fixed by #288.

In case there still are problems please reopen this issue.
