### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/createrepo_c#273]
0.17.2 and 0.17.3 are tagged, but the releases weren't created on Github

**Comment by kontura** [comment]
Sorry about that.
I have created the Github releases for both of them.

**Comment by kontura** [comment]
Hm, looks like the automatic python release action failed: https://github.com/rpm-software-management/createrepo_c/runs/3006511969?check_suite_focus=true

**Comment by dralley** [comment]
@kontura Maybe double check the credentials?

**Comment by dralley** [comment]
It worked! https://pypi.org/project/createrepo-c/

Thanks
