### ISSUE TITLE
discussion: createrepo with RPMs in s3

### ISSUE THREAD

**Issue by ktdreyer** [rpm-software-management/createrepo_c#278]
Today createrepo does a lot of local filesystem reads (`g_dir_open`, `Fopen`, etc).

For a while I've been thinking about the idea of storing RPMs in object storage (s3) and then running some createrepo-like tool on the RPMs in-place, without having to download them all locally. This would allow us to store many RPMs in an S3 bucket (sort of like how we use `/mnt/koij` or `/mnt/redhat` today).

When I upload each RPM, I could store the RPM headers as attributes on each object, and then read that metadata with the createrepo-like tool (sort of like `rpmReadPackageFile()`).

When generating the repo metadata, the tool could write out the full URLs into `primary.xml`, like with `<location href="https://s3.example.com/coolpackage-1.0.rpm"/>`, so that clients download the RPMs directly from the S3 URL.

What sort of things would I need to consider in order to implement a project like this? Is this idea crazy?

**Comment by dmach** [comment]
The idea is not crazy, you seem to have a good use case.
On the other hand, I'm not sure if this wouldn't be too specific for AWS.

I'm wondering if writing a createrepo_c plugin (data source) tailored to this use case or writing a new tool that would use some createrepo_c internals wouldn't be a better option.

We also don't have this on our short/mid-term priority list, we should be rather working on dnf 5.

If you want to discuss this in more detail, just ping me and we can schedule a call.

**Comment by ktdreyer** [comment]
Thanks @dmach .

Ceph has robust support for AWS's S3 APIs, and Google supports some S3 APIs. It's becoming the de-facto standard for large object storage deployments.

I'll look more into this and try writing a simple prototype.

**Comment by dralley** [comment]
@ktdreyer Pulp 3 supports AWS as a storage backend, for what it's worth :)

https://pulpproject.org/features/#multiple-storage-options

Not sure whether or not your particular use case calls for a heavyweight tool, though - I messaged you on Gchat in case you'd like to discuss.

**Comment by ktdreyer** [comment]
Yeah, I'm thinking about how we would use an s3 bucket as a Koji volume. Currently all Koji volumes are simply NFS mounts that Apache serves with HTTP.

**Comment by dralley** [comment]
FYI I started working on a CLI tool for which this could potentially be an interesting feature https://github.com/dralley/rpmrepo

Right now it only does the two things I immediately had a use for - downloading repos and checking for problems.  (And it's garbage code because I've not spend a lot of effort on it yet).

But "managing" them even if the files weren't on-disk would also be interesting.

**Comment by ktdreyer** [comment]
Thanks for the evaluation here @dmach . I will close this for now.

**Comment by ktdreyer** [comment]
For future research: I found some code at https://github.com/jbraeuer/yum-s3-plugin that has some similar ideas.

**Comment by dralley** [comment]
There's also this which is only tangentially related https://github.com/mamba-org/powerloader

**Comment by ktdreyer** [comment]
In Rocky Linux, along with the individual RPMs they upload into their archival system, they also upload the output from running `createrepo` individually on each RPM. This allows them to quickly pull down all the XML files for each RPM they want to compose, merge those together, and then publish that combined repository metadata. This allows them to update large Yum repos without having to download all the RPMs and read them all through createrepo each time. More explanation at https://github.com/rocky-linux/peridot/blob/a2aef0460ed73dd49b228c5589c00b669196a6a1/docs/yumrepofs.md

**Comment by dralley** [comment]
That's similar-ish to what Pulp does, except Pulp stores the metadata in a Postgresql database.
