### ISSUE TITLE
createrepo_c --update can corrupt dependencies

### ISSUE THREAD

**Issue by mlschroe** [rpm-software-management/createrepo_c#286]
The centos-8 bpg-algeti-fonts-2.005-11.el8.noarch.rpm package contains the provides `font(bpgalgetigpl&gnu)`.
This ends up in primary.xml file like this:
```
<rpm:entry name="font(bpgalgetigpl&amp;gnu)"/>
```

For some unknown reason, libxml2 re-escapes '&' characters in attributes (unlike libexpat). Any `&` character will be replaced by `&#38;`. This means that a createrepo_c --update operation will write a bad dependency line:
```
<rpm:entry name="font(bpgalgetigpl&amp;#38;gnu)"/>
```

(libsolv suffers from the same issue. I fixed it with https://github.com/openSUSE/libsolv/commit/9a13593b43bd883be6bf4260edbfc8eaf766ffa8)

**Comment by kontura** [comment]
I have made a PR: https://github.com/rpm-software-management/createrepo_c/pull/289
It uses a different approach than libsolv.

**Comment by dralley** [comment]
Ultimately the issue is not that it re-encodes the entities but that they are not decoded by the parsing in the first place.  We're reading these values and then saving them to the database, and they're incorrect (because the encoding wasn't reversed)
