### ISSUE TITLE
Bogus warning emitted: "Requested more delta workers than workers. This is insane. Limiting."

### ISSUE THREAD

**Issue by archiecobbs** [rpm-software-management/createrepo_c#298]
On a multi-core machine, createrepo generates a bogus warning:

```bash
    $ grep ^proc /proc/cpuinfo | wc -l
    4
    $ mkdir foo
    $ createrepo foo
    Warning: Requested more delta workers than workers. This is insane. Limiting.
    Saving Primary metadata
    Saving file lists metadata
    Saving other metadata
```

It's silly for a tool to emit a warning like that when running in it's default configuration.

This glitch only occurs on a multi-core machine, so it seems to relate to how the default configuration is calculated in this scenario.

createrepo-0.10.4-lp152.5.4.x86_64
openSUSE Leap 15.2

[Original openSUSE bug](https://bugzilla.suse.com/show_bug.cgi?id=1193495).

**Comment by Conan-Kudo** [comment]
Have you tried with the latest version of createrepo_c (0.17.3) in openSUSE Tumbleweed, or the version in Leap 15.3 (0.15.4)?

**Comment by archiecobbs** [comment]
I just realized openSUSE Leap 15.3 has two different versions of "createrepo" (`createrepo` and `createrepo_c`).

And they can both be installed at the same time with `/etc/alternatives`:
```bash
$ rpm -qa | grep createrepo
libcreaterepo_c0-0.16.0-3.3.1.x86_64
createrepo_c-0.16.0-3.3.1.x86_64
createrepo-0.10.4-bp153.1.12.x86_64
```

So now I'm a little confused about where to report this bug. When I [reported it to openSUSE](https://bugzilla.suse.com/show_bug.cgi?id=1193495) they told me to go away and report it here instead.

But this bug occurs with `createrepo` but not `createrepo_c`. So this doesn't seem like the right place to report it after all.

Sorry, nevermind!
