### ISSUE TITLE
File "/root/dem/bin/cmake", line 5, in from cmake import cmake ModuleNotFoundError: No module named 'cmake'

### ISSUE THREAD

**Issue by jringoot** [rpm-software-management/createrepo_c#299]
I am trying to install createrepo_c (to install cobbler on ubuntu)
I have this weird error that there is no module cmake while importing cmake while cmake is installed with pip

> (dem) root@easy-install-me:~# python -m pip install createrepo_c
> Collecting createrepo_c
> Using cached createrepo_c-0.17.6.tar.gz (805 kB)
> Installing build dependencies ... done
> Getting requirements to build wheel ... done
> Preparing metadata (pyproject.toml) ... done
> Building wheels for collected packages: createrepo-c
> Building wheel for createrepo-c (pyproject.toml) ... error
> ERROR: Command errored out with exit status 1:
> command: /root/dem/bin/python /root/dem/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp2mdtevj8
> cwd: /tmp/pip-install-rz7uielw/createrepo-c_f82d45a034e74c8f9988db10bec235fb
> Complete output (13 lines):
> Traceback (most recent call last):
> File "/root/dem/bin/cmake", line 5, in
> from cmake import cmake
> ModuleNotFoundError: No module named 'cmake'
> File "/tmp/pip-build-env-dzo889fa/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 564, in setup
> cmkr = cmaker.CMaker(cmake_executable)
> File "/tmp/pip-build-env-dzo889fa/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 95, in init
> self.cmake_version = get_cmake_version(self.cmake_executable)
> File "/tmp/pip-build-env-dzo889fa/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 81, in get_cmake_version
> raise SKBuildError(
> Traceback (most recent call last):
> 
> Problem with the CMake installation, aborting build. CMake executable is cmake
> ERROR: Failed building wheel for createrepo-c
> Failed to build createrepo-c
> ERROR: Could not build wheels for createrepo-c, which is required to install pyproject.toml-based projects
> (dem) root@easy-install-me:~# python -m pip install --upgrade cmake
> 
> Requirement already satisfied: cmake in ./dem/lib/python3.8/site-packages (3.22.1)
> 
> (dem) root@easy-install-me:# python -m pip install --upgrade pip
> Requirement already satisfied: pip in ./dem/lib/python3.8/site-packages (21.3.1)
> (dem) root@easy-install-me:#

See also
https://github.com/pypa/pip/issues/10730

**Comment by kontura** [comment]
The `SKBuildError` appers to be coming from [here](https://github.com/scikit-build/scikit-build/blob/a7c746ae47d27b641f5734103e8fa4aaaabc09e3/skbuild/cmaker.py#L78-L82). Can you execute `$ cmake --version`?

Perhaps you don't have `cmake` installed (`$ apt-get install cmake`).

**Comment by kontura** [comment]
I believe this was not an issue in createrepo_c.
