### ISSUE TITLE
Please write proper commit messages

### ISSUE THREAD

**Issue by ac000** [rpm-software-management/createrepo_c#30]
Hi, while perusing the commit log of this repository one thing instantly struck me. The lack of actual commit messages.

Sure there's a one line (sometimes too long a line) summary but where's the rest? Not too easy to follow what's going on.

Here's what a good commit message should generally look like.
https://github.com/torvalds/subsurface/blob/master/README#L87

If you want more real-world examples of generally good commit messages, just browse the Linux Kernels log

Cheers,
Andrew

**Comment by Tojaj** [comment]
Hi,
I'll try to be more verbose in my future commit messages.

* 0240c8ecee1bde3523f33705daea8c0ddce8893a
* b9150a0d4990f47e120f817ce16d250333b89fb7
* 215b5973370699d4c350e89fe7540bc5d4b79093

**Comment by ac000** [comment]
On Thu, 08 Oct 2015 02:51:02 -0700, Tomas Mlcoch wrote:

> Hi,
> I'll try to be more verbose in my future commit messages.
> 
> * 0240c8ecee1bde3523f33705daea8c0ddce8893a
> * b9150a0d4990f47e120f817ce16d250333b89fb7
> * 215b5973370699d4c350e89fe7540bc5d4b79093

Ah, yes, much better! :) You've just elevated yourself above 90% of
what's on GitHub.

It is of course your project and you can write commit messages however
you want, but good commit messages really are important and maybe in
six months time when you need to refer back to something, you'll be
grateful for having them. 

Cheers,
Andrew
