### ISSUE TITLE
bad character in updateinfo causes parse error "PCDATA invalid Char value 27"

### ISSUE THREAD

**Issue by aranc23** [rpm-software-management/createrepo_c#314]
I'm using 0.17.6 as a component of pulp.
A recent Fedora errata includes an invalid character in the description field, which causes createrepo to fail when parsing the updateinfo file.

 https://mirror.math.princeton.edu/pub/fedora/linux/updates/34/Everything/x86_64/repodata/0f8d7e05e16bc6ee836c359b6fb521440d67f47385e7396d14d8f53fac4a7343-updateinfo.xml.xz

If you try to open that file in chrome it will show the same error message.  I examined it in emacs and sure enough on that line the description for the errata contains some escaped character.  

I guess Fedora should fix their errata, but I don't think there is a way to avoid this happening in the future so hopefully createrepo can do something sensible about invalid characters when parsing?  

The traceback from pulp trimmed:
File \"/usr/local/lib/pulp/lib64/python3.8/site-packages/pulp_rpm/app/tasks/synchronizing.py\", line 695, in parse_updateinfo
   cr.xml_parse_updateinfo(updateinfo_xml_path, uinfo)
  File \"/usr/local/lib/pulp/lib64/python3.8/site-packages/createrepo_c/__init__.py\", line 342, in xml_parse_updateinfo
    return _createrepo_c.xml_parse_updateinfo(path, updateinfoobj, warningcb)\n",
   
"Parse error '/var/lib/pulp/tmp/1107@pulp3test01.divms.uiowa.edu/tmps5ja67jl/tmp9de6zkcc' at line: 120516 (PCDATA invalid Char value 27\n)"

**Comment by dralley** [comment]
This was a Bodhi issue, there's really nothing createrepo_c can do here.  The XML isn't valid, libxml complains for valid reasons.

It's fixed now though.

https://github.com/fedora-infra/bodhi/issues/4422
