### ISSUE TITLE
Changelog limit doesn't work properly with --compatibility

### ISSUE THREAD

**Issue by andrewlukoshko** [rpm-software-management/createrepo_c#318]
If run `createrepo_c --compatibility --changelog-limit=10 .` then changelog will not be limited because of this code:
https://github.com/rpm-software-management/createrepo_c/blob/ace4c87a392b8c25fd7127da49516dba52d397c9/src/createrepo_c.c#L1262
```
    if (cmd_options->compatibility && cmd_options->changelog_limit == DEFAULT_CHANGELOG_LIMIT ) {
      user_data.changelog_limit   = -1;
    } else {
      user_data.changelog_limit   = cmd_options->changelog_limit;
    }
```
I'm pretty sure --changelog-limit=10 should force limit.

**Comment by kontura** [comment]
Thank you for the report, I think the `--compatibility` option is not used very much so this issue has a low priority for us right now.
