### ISSUE TITLE
createrepo_c.PackageIterator yeilds no packages when filelists.xml.gz is empty

### ISSUE THREAD

**Issue by apatters** [rpm-software-management/createrepo_c#329]
[Pulp 3](https://pulpproject.org/about-pulp-3/) uses `createrepo_c.PackageIterator() in the createrepo_c` python module used to iterate through a set of available packages when syncing repositories, This iterator will return empty if the the corresponding repository `filelists.xml.gz` file is empty like when used with certain "degenerate" repositories (example: https://packages.gitlab.com/gitlab/gitlab-ee/el/8/x86_64).  The `createrepo_c.xml_parse_primary`method  seems to work normally. I tested this using the example code at https://github.com/rpm-software-management/createrepo_c/blob/master/examples/python/repodata_parsing.py

```python
import createrepo_c as cr
.
.
.
for pkg in parser.as_iterator():
                pkg_nevra = pkg.nevra()
.
.
.
```

See https://pulp.plan.io/issues/1287 for a detailed explanation on why the `filelists.xml.gz` file is empty. Although, this type of repo probably does not meet the RPM repository spec, standard tools like reposync work fine with it. It would be nice if this iterator would return the package list despite the lack of contents in `filelists.xml.gz` so it could work with Pulp.

**Comment by dralley** [comment]
@apatters As it turns out, I reported this to packagecloud.io a few months back (they handle hosting the gitlab repos) and managed to get them to fix the issue.  

And as of yesterday it looks like gitlab updated their repos in such a way that the metadata finally got refreshed, so it probably ought to be working now.

**Comment by dralley** [comment]
I tested it and it does ^^

So I would suggest we don't make this particular change, although at the moment it is still impossible to pass a null for filelists or changelog xml without causing a segfault, when it perhaps ought to be optional to parse them.

**Comment by apatters** [comment]
@dralley I am confused. I last tested this a few weeks ago and the iterator was not returning any packages with an empty `filelists.xml.gz` file. We have deliberately configured PackageCloud to use the empty file for GitLab repos due to size issues as detailed above. What issue did PackageCloud fix? Should I retest?

**Comment by dralley** [comment]
The file list file is no longer empty.  It correctly lists entries for each package.

**Comment by apatters** [comment]
And so it is. It looks like they are now showing packages but that the files in each package:

```text
<?xml version="1.0" encoding="UTF-8"?>
<filelists xmlns="http://linux.duke.edu/metadata/filelists" packages="276">
  <package pkgid="3b9f99f37013e4eb88293d04b53137c86b0fd679" name="gitlab-ee" arc
h="x86_64">
    <version epoch="0" ver="12.10.0" rel="ee.0.el8"/>
  </package>
.
.
.
<package pkgid="18b3214a19206f9b0727bfb024ae6c1da21dc9eb" name="gitlab-ee" arch="x86_64">
    <version epoch="0" ver="15.5.4" rel="ee.0.el8"/>
  </package>
</filelists>
```

Which works fine with pulp 3. Thanks!

**Comment by dralley** [comment]
FWIW I would think this can be closed now.
