### ISSUE TITLE
Simplify cr_get_header_byte_range() + possible efficiency improvment?

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/createrepo_c#332]
I'm curious if `headerSizeof()` from librpm can be used to replace much of the existing logic for [`cr_get_header_byte_range()`](https://github.com/rpm-software-management/createrepo_c/blob/d1d12ddc474391ea738cf713329da080eb5346ee/src/misc.c#L244-L350).

The way I understand the algorithm of `cr_header_byte_range()` is

```
headerStart = 112 (some magic constant representing the size of the Lead?) + signature header size + padding to some kind of alignment
headerEnd = headerStart + index header size
```

createrepo_c already has to extract and parse the header from the package anyway, so why not just use [`headerSizeof()`](https://github.com/rpm-software-management/rpm/blob/master/include/rpm/header.h#L63) from `rpmio` to calculate the sizes of the headers, and simplify the implementation from ~100 lines to just a couple of lines (essentially just the pseudocode above)

As a side benefit this would avoid having to open the file an extra time and seek around.

Is my understanding of how it works correct? (especially the magic numbers.  https://rpm-software-management.github.io/rpm/manual/format.html claims that the Lead is 96 bytes including the magic number, but it's not clear how we get from 96 to 112 or the constant 104 on line 275)

**Comment by dralley** [comment]
Separately: this kind of feels like functionality that librpm ought to provide rather than be implemented in createrepo_c.  createrepo_c  shouldn't be in the business of parsing RPM files and making assumptions about their structure?

**Comment by j-mracek** [comment]
I think it sound reasonable to remove part of the code in createrepo_c and replace it by calling function from rpm-libs.

In the first place we have to investigate whether both functions returns compatible outputs.

In the second part we have to ask RPM team whether they would expose `headerSizeof()` as API. May I ask you @pmatilai for an opinion?

**Comment by dralley** [comment]
I think it's already exposed?  It's listed in the documentation.

**Comment by dralley** [comment]
@pmatilai see discussion

**Comment by dralley** [comment]
Maybe the reason is that there isn't a version of `rpmReadPackageFile()` / `rpmReadHeader()` that works with the signature header?  If you can't calculate the size / padding, you can't finish the calculation.

**Comment by dralley** [comment]
I did eventually figure out the magic constants, I'll make a PR eventually to clean the code up a bit.

**Comment by dralley** [comment]
The fact that there's no way to get back a pair of signature and normal headers, and that the API merges the headers together, makes this impossible.
