### ISSUE TITLE
rpm for x86_64 vanished from EPEL7

### ISSUE THREAD

**Issue by kwyxz** [rpm-software-management/createrepo_c#333]
Hello maintainers, 
It looks like the `createrepo_c` 0.10.0 package, which used to be in EPEL7 for x86_64, has disappeared.
This causes `mock` to be uninstallable on RHEL7 systems.
Could the package please be pushed back to EPEL7?
Thank you.

**Comment by kontura** [comment]
This might be just me since I am not that well versed in rhel 7 repos but I cannot find it. 
I do see old [createrepo](https://github.com/rpm-software-management/createrepo) though, perhaps there was a confusion with `createrepo`  vs. `createrepo_c`? @carlwgeorge

**Comment by kwyxz** [comment]
Ditto, after adding the extras repo to the yum list, the package installs. Thank you for your help.
