### ISSUE TITLE
[1.0 breaking change] - Don't generate sqlite metadata by default

### ISSUE THREAD

**Issue by dralley** [rpm-software-management/createrepo_c#338]
yum supports XML metadata even though it prefers sqlite, but DNF doesn't use sqlite metadata at all.  Since generating and compressing the sqlite metadata is [very expensive](https://github.com/rpm-software-management/createrepo_c/pull/335#issuecomment-1381367434) and removing it should not break compatibility with RHEL, and also provides no benefit nowadays, it might be reasonable to disable it by default, or even compile the feature out by default on most platforms.

The only two non-yum users I am aware of are: [mdapi](https://pagure.io/releng/issue/10745), and repoview.  repoview is defunct, and the fedora infra looks like it specifically adds --database or --no-database as needed so the default shouldn't affect it, which means mdapi shouldn't be broken by a change in default.

It would probably be good to update that eventually, though.

**Comment by j-mracek** [comment]
I also support to change the default to not generate yum database as default. Note - such a change cannot be back-ported to RHEL.

**Comment by dralley** [comment]
Suggestion - given the changes proposed for "1.0" in https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/25J55FCQKTMCEOBS7EZCTP34RKLUOUQ3/, I propose we go a tiny bit further.

* `sqliterepo_c` could be split into a new package so that it could be removed at some point in the future without breaking semantic versioning
    * EL7 is the only significant beneficiary, and EL7 will be EOL in a year
* The --database and --no-database options could be dropped entirely in favor of users deliberately calling `sqliterepo_c`
    * Likewise re: EL7.  Additionally as per the proposal `createrepo_c` would not necessarily generate EL7-compatible repos by default due to the treatment of comps metadata - this would be an even less significant impedance than that

**Comment by dralley** [comment]
@kontura The original proposal here is finished, should we close this and file new issues for dropping --no-database?

**Comment by kontura** [comment]
> @kontura The original proposal here is finished, should we close this and file new issues for dropping --no-database?

That sounds good. :+1:
