### ISSUE TITLE
Can createrepo_c generate shared pools?

### ISSUE THREAD

**Issue by jketreno** [rpm-software-management/createrepo_c#344]
I am trying to create a shared file pool across multiple RPM repositories.

For example:

Packages:
/pool/l/libfoo-1.0.rpm
/pool/l/libfoo-1.1.rpm
/pool/m/mypackage-0.1.rpm

Repositories:
/latest/repodata points to libfoo-1.1.rpm and mypackage-0.1.rpm
/stable/repodata points to libfoo-1.0.rpm and mypackage-0.1.rpm

I don't want to replicate the package disk storage for each instance of the same package. Currently I put a symlink in /latest/pool => ../pool and /stable/pool => ../pool.

I then run createrepo_c via:

```
createrepo_c -v --location-prefix="../" /latest
```

It then correctly puts the relative path in the primary list to "../pool/l/libfoo-1.1.rpm" correctly, but it requires me to have the symlink from /latest/pool to /pool/ in order for it to index correctly.

Is the right approach? I tried using "--basedir=/pool" but that didn't seem to index the files.

Is there a way to tell createrepo_c to index /pool and put full relative paths in the repodata filelists without the use of the symlink?

**Comment by dralley** [comment]
What is your ultimate goal?  You could use [Pulp](https://pulpproject.org/) for this.

**Comment by jketreno** [comment]
I hadn't come across Pulp -- I'll look into it. Thank you.

The goal is to provide package repositories for .deb and .rpm for multiple distros, and be able to snapshot the repositories with time-based names.

If the same package exists in multiple snapshots, we want to use a shared package pool for that distro so the packages aren't replicated on disk into each snapshot location.  With [reprepro](https://salsa.debian.org/brlink/reprepro),  a shared pool is available. I am trying to recreate similar behavior with createrepo_c.

**Comment by dralley** [comment]
That is more or less what Pulp is for - versioned repositories, deduplicated storage on the backend, S3 and Azure support etc.

**Comment by kontura** [comment]
> Is there a way to tell createrepo_c to index /pool and put full relative paths in the repodata filelists without the use of the symlink?

If you want repodata in `latest` given your packages, so:
```
/pool/l/libfoo-1.0.rpm
/pool/l/libfoo-1.1.rpm
/pool/m/mypackage-0.1.rpm
/latest/
```
I think you could also do something like this (running from `/`):
```
createrepo_c --outputdir latest/ --location-prefix="../pool" pool
```

Or perhaps like mentioned Pulp could provide a more complete solution.
