### ISSUE TITLE
Invalid C in cmd_parser.c - fails compile

### ISSUE THREAD

**Issue by sjwinn** [rpm-software-management/createrepo_c#357]
[ 63%] Building C object src/CMakeFiles/createrepo_c.dir/cmd_parser.c.o
/var/lib/go-agent/pipelines/createrepo-c/createrepo_c-0.21.1/src/cmd_parser.c: In function ‘duplicated_nevra_option_parser’:
/var/lib/go-agent/pipelines/createrepo-c/createrepo_c-0.21.1/src/cmd_parser.c:76:32: error: parameter name omitted
   76 | duplicated_nevra_option_parser(const gchar *,
      |                                ^~~~~~~~~~~~~
/var/lib/go-agent/pipelines/createrepo-c/createrepo_c-0.21.1/src/cmd_parser.c:78:32: error: parameter name omitted
   78 |                                gpointer,
      |                                ^~~~~~~~
make[4]: Leaving directory '/var/lib/go-agent/pipelines/createrepo-c/createrepo_c-0.21.1/build'
make[4]: *** [src/CMakeFiles/createrepo_c.dir/build.make:76: src/CMakeFiles/createrepo_c.dir/cmd_parser.c.o] Error 1

Well, yes, that's very much invalid in classic C - variable names are not optional. 

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

Just needs dummy names if they're not being used.

**Comment by andreatomassetti** [comment]
Same issue here. Last version that compiles is 0.20.1 (af14e16)

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by kontura** [comment]
This should be resolved by: https://github.com/rpm-software-management/createrepo_c/pull/366
