### ISSUE TITLE
Typo/mixed tense "doesn't exists" in several locations

### ISSUE THREAD

**Issue by rxguy** [rpm-software-management/createrepo_c#358]
Hello all.
This is certainly not much of a bug report, however it is something I noticed in an error message while running createrepo: "Old repodata doesn't exists".

This should say: "Old repodata doesn't exist".

Upon inspection, I noticed "doesn't exists" occurs multiple times:
(I ran `grep -Hinr "doesn't exists" *`)

src/cmd_parser.c:389:                    "Specified outputdir \"%s\" doesn't exists",
src/cmd_parser.c:501:                        "groupfile %s doesn't exists",
src/cmd_parser.c:511:                        "pkglist file \"%s\" doesn't exists", options->pkglist);
src/compression_wrapper.c:130:        g_debug("%s: File %s doesn't exists or not a regular file",
src/compression_wrapper.c:133:                    "File %s doesn't exists or not a regular file", filename);
src/createrepo_c.c:2478:        g_debug("Old repodata doesn't exists: Cannot rename %s -> %s: %s",
src/createrepo_shared.h:78: * - If it doesn't exists, it's created and function returns TRUE.
src/error.h:44:        (8) Directory doesn't exist (not a dir or path doesn't exists) */
src/locate_metadata.c:213:        g_debug("%s: %s doesn't exists", __func__, repomd);
src/mergerepo_c.c:332:            g_critical("File %s doesn't exists", options->blocked);
src/misc.h:550: * If one of the files doesn't exists, the funcion doesn't fail
src/modifyrepo_c.c:221:                    "File \"%s\" is not regular file or doesn't exists",
src/modifyrepo_shared.c:147:                    "Regular file \"%s\" doesn't exists", repomd_path);
src/modifyrepo_shared.c:244:            // Check if record with this name doesn't exists yet
src/repomd.c:128:                    "File %s doesn't exists or not a regular file", filename);
src/repomd.c:234:        // File doesn't exists
src/repomd.c:235:        g_warning("%s: File %s doesn't exists", __func__, path);
src/repomd.c:237:                    "File %s doesn't exists or not a regular file", path);
src/repomd.c:373:        // File doesn't exists
src/repomd.c:374:        g_warning("%s: File %s doesn't exists", __func__, record->location_real);
src/repomd.c:376:                    "File %s doesn't exists or not a regular file",
tests/python/tests/test_parsepkg.py:42:        # Rpm doesn't exists
tests/python/tests/test_parsepkg.py:61:        # Rpm doesn't exists
utils/speed_test.sh:48:    echo "Directory $REPO doesn't exists"

**Comment by m-blaha** [comment]
Thanks! Are you willing to create a patch for it (greatly appreciated)?

**Comment by rxguy** [comment]
I will attempt a pull request. Fair warning: I am VERY inexperienced with this sort of thing.
