### ISSUE TITLE
[FIX] Build from 'master' branch is broken

### ISSUE THREAD

**Issue by SchweinDeBurg** [rpm-software-management/createrepo_c#369]
[fix.patch.txt](https://github.com/rpm-software-management/createrepo_c/files/11489640/fix.patch.txt)

**Comment by kontura** [comment]
Can you provide a reproducer for when the build fails?

I am curios what am I missing because it is working for me.

**Comment by SchweinDeBurg** [comment]
I am using GCC version 9.3 and got three compile errors. Here is my RPM spec file: [fish-3.6.1-fedora.spec.txt](https://github.com/rpm-software-management/createrepo_c/files/11494572/fish-3.6.1-fedora.spec.txt).

**Comment by SchweinDeBurg** [comment]
I am using GCC version 9.3 and got three compile errors without this fix. Here is my RPM spec file: [createrepo_c-0.21.1-fedora.spec.txt](https://github.com/rpm-software-management/createrepo_c/files/11494590/createrepo_c-0.21.1-fedora.spec.txt).

**Comment by kontura** [comment]
I see, its the:
```
error: a label can only be part of a statement and a declaration is not a statement
```
which seems to work in newer gcc.
