### ISSUE TITLE
[RFE] Provide a Python 3 API

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/createrepo_c#41]
Currently createrepo_c offers a Python 2 API, but it does not offer a Python 3 API to go with it. 

Please add a Python 3 API to createrepo_c for those who want to have their programs use Python 3 instead of Python 2.

**Comment by ralphbean** [comment]
I started poking at this over on a [python 3 branch](https://github.com/ralphbean/createrepo_c/tree/python3).
