### ISSUE TITLE
Allow parsing packages metadata without filelists

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/createrepo_c#423]
Since Fedora 40, as [filelists are not present in the dnf cache by default](https://fedoraproject.org/wiki/Changes/DNFConditionalFilelists), we should consider making it optional also when parsing XML files in createrepo_c, specifically in `cr_PkgIterator` and the underlying structures.

Several related TODOs are already present in the code in [xml_parser_main_metadata_together.c](https://github.com/rpm-software-management/createrepo_c/blob/1.0.4/src/xml_parser_main_metadata_together.c#L394).

**Comment by dralley** [comment]
They mean that when using the `cr_PkgIterator` API, you should be able to leave the filelists xml or other xml arguments as null.
