### ISSUE TITLE
Why remove the uncompressed XML files from repodata?

### ISSUE THREAD

**Issue by PshySimon** [rpm-software-management/createrepo_c#431]
I'm confused about this commit, https://github.com/rpm-software-management/createrepo_c/pull/373/commits/22eb96fd66dab0a8756a65919ea98272b4d1c49b, which remove uncompressed XML files from repodata.
I want to know what specific impact does this operation have?

Btw, I noticed in the changelog that there is mention of incompatibility with yum, specifically, where exactly is the incompatibility located?

**Comment by ppisar** [comment]
My understanding: The way how some files were compressed diverged over the time. Some were compressed, some kept uncompressed. I believe that commit was an attempt to unify the compression. One of the reasons was some files were kept uncompressed were bugs in old yum versions which forgot to support a compression on that files. That's the incompatibility.

More details could provide you an author of that commit.

**Comment by ppisar** [comment]
If you are fine with the answer, I will close this issue.

**Comment by dralley** [comment]
That answer is essentially correct.  If you need to use a new very version of  `createrepo_c` with an old distribution thta uses `yum`, please use the `--compatibility` flag.
