### ISSUE TITLE
Add option to createrepo_c to disable reading/writing .xml files

### ISSUE THREAD

**Issue by jailbird777** [rpm-software-management/createrepo_c#45]
6.x & 7.x of the distros don't require the .xml version of the metadata, only the .sqlite files.  https://github.com/heroldus/updaterepo disabled the .xml files to speed up creation/updates.  createrepo_c should add an option to do the same.

**Comment by Conan-Kudo** [comment]
@jailbird777 SQLite database metadata format is being retired. Yum's successor, DNF, doesn't even use them at all, because libsolv handles the XML format far more efficiently.

It's far more likely that in RHEL 8.x, you'll see the SQLite database version of the metadata disappear entirely.

**Comment by jailbird777** [comment]
Understood, thanks!
