### ISSUE TITLE
src/misc.c:421: 2 * resource leak ?

### ISSUE THREAD

**Issue by dcb314** [rpm-software-management/createrepo_c#47]
1.

createrepo_c/src/misc.c:421]: (error) Resource leak: orig

$ fgrep -n orig ../BUILD/createrepo_c/src/misc.c
373:    _cleanup_file_fclose_ FILE *orig = NULL;
387:    if ((orig = fopen(src, "rb")) == NULL) {
405:    while ((readed = fread(buf, 1, BUFFER_SIZE, orig)) > 0) {
406:        if (readed != BUFFER_SIZE && ferror(orig)) {

2.

createrepo_c/src/misc.c:421]: (error) Resource leak: new

$ fgrep -n new ../BUILD/createrepo_c/src/misc.c
374:    _cleanup_file_fclose_ FILE *new  = NULL;
396:    if ((new = fopen(dst, "wb")) == NULL) {
412:        if (fwrite(buf, 1, readed, new) != readed) {

**Comment by Conan-Kudo** [comment]
This is not helpful. What are you trying to convey?

**Comment by dcb314** [comment]
I just noticed the cleanup_file_fclose. False alarm. Sorry.

**Comment by Conan-Kudo** [comment]
Please close the issue if it isn't a problem.
