### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/createrepo_c#48]
Some parameters (like "[${LIBXML2_INCLUDE_DIR}](https://github.com/rpm-software-management/createrepo_c/blob/e0b32cb06477150504cf5bab29e463670fcaa44c/CMakeLists.txt#L41)" and "[${LIB_INSTALL_DIR}](https://github.com/rpm-software-management/createrepo_c/blob/c1fb1f0bcc016869a38c511ff1b2c764503d92ca/src/CMakeLists.txt#L117)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by Conan-Kudo** [comment]
@elfring By all means, make a pull request to fix this. @Tojaj happily accepts patches through pull requests.
