### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/createrepo_c#49]
I would like to point out that an identifier like "[`__C_CREATEREPOLIB_CMD_PARSER_H__`](https://github.com/rpm-software-management/createrepo_c/blob/0240c8ecee1bde3523f33705daea8c0ddce8893a/src/cmd_parser.h#L20)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Conan-Kudo** [comment]
@elfring By all means, make a pull request to fix this. @Tojaj happily accepts patches through pull requests.
