### ISSUE TITLE
Check return codes everywhere

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/createrepo_c#50]
Would you like to add more error handling for return values from functions like the following?
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [main](https://github.com/rpm-software-management/createrepo_c/blob/b9150a0d4990f47e120f817ce16d250333b89fb7/src/createrepo_c.c#L318)
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html) ⇒ [cr_set_cleanup_handler](https://github.com/rpm-software-management/createrepo_c/blob/6e0d5f2ad2be3253be3712c1945f6486d81c0cee/src/createrepo_shared.c#L72)

**Comment by Conan-Kudo** [comment]
@elfring By all means, make a pull request to fix this. @Tojaj happily accepts patches through pull requests.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by ferdnyc** [comment]
LOL, is this really robospam via GitHub issue? That's pretty hilarious!

(Probably not so much if you're on the receiving end, sorry.)
