### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [rpm-software-management/createrepo_c#51]
The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html)" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers).
I guess that a different program design will be needed for your function "[sigint_catcher](https://github.com/rpm-software-management/createrepo_c/blob/6e0d5f2ad2be3253be3712c1945f6486d81c0cee/src/createrepo_shared.c#L62)".

**Comment by Conan-Kudo** [comment]
@elfring By all means, make a pull request to fix this. @Tojaj happily accepts patches through pull requests.

**Comment by elfring** [comment]
Would you like to consider other software design options?
* [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html "wait for queued signals")
* [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html "Use case description by Daniel J. Bernstein")
* [Signal-safe locks](http://locklessinc.com/articles/signalsafe_locks/ "lock-free algorithms")
