### ISSUE TITLE
Exit status should not be 0 on failure

### ISSUE THREAD

**Issue by nbartos** [rpm-software-management/createrepo_c#58]
When there is an issue opening a file (for example, a broken symlink), the error is reported, however the exit status still reports success.

The original createrepo returns failure if an error occurs opening a file.  While I really, really want to use createrepo_c because of the amazing speed, until this is fixed I have no choice but to use the older, slower, createrepo.

**Comment by noelbk** [comment]
Here's a PR: https://github.com/rpm-software-management/createrepo_c/pull/63
