### ISSUE TITLE
Include metadata md5 checksum in repomd.xml schema for repo metadata files

### ISSUE THREAD

**Issue by robnester** [rpm-software-management/createrepo_c#60]
I'd like to find out if the schema for repomd.xml can be modified to include an additional entry in:

`<!ELEMENT data (location | checksum | timestamp | open-checksum | open-size | size | database_version)+> `
seen here:
https://github.com/rpm-software-management/yum/blob/master/docs/repomd.dtd

which could hold an additional MD5 checksum for the repo metadata files. 

Would this cause any issues with existing clients if so, or would clients ignore "extraneous" elements that they're not using?

**Comment by Tojaj** [comment]
I cannot spoke for others, but Createrepo_c just ignore elements it doesn't know. It's a form of forward-compatibility. I'm not sure about yum, but afaik it should behave in the same way if nothing changed.

Also I suggest you to subscribe to rpm-ecosystem [1] mailing list and you may try ask there.

Btw. why would you like to include additional checksum? There are already two checksum elements (one for compressed metadata file and the second for the decompressed data) and both of them have attribute **type**. Why not use the already available element, and just put there the MD5 checksum and appropriate type (md5)?

[1] http://lists.rpm.org/mailman/listinfo/rpm-ecosystem

**Comment by robnester** [comment]
@Tojaj The desire for an additional checksum relates to content validation testing. Our CDN provides MD5 checksums for files as a header. If we have the MD5 of the given repo metadata file in repomd.xml it simplifies and accelerates testing, as we do not have to download the entire metadata file to perform a checksum on it.

Or, are you suggesting that we can have another checksum element with a different checksum type such as:

```
<data type="other_db">
<location href="repodata/(file_name).sqlite.bz2"/>
<checksum type="sha">(checksum)</checksum>
<checksum type="md5">(checksum)</checksum>
<timestamp>1463082138.0</timestamp>
<size>5849902</size>
<open-size>50198528</open-size>
<open-checksum type="sha">(checksum)</open-checksum>
<database_version>10</database_version>
</data>

```
