### ISSUE TITLE
SIGSEGV when reading updateinfo

### ISSUE THREAD

**Issue by dmach** [rpm-software-management/createrepo_c#72]
I'm reading hundreds of updateinfo.xml files in 10 threads in Python.

I end up with SIGSEGV, Segmentation fault.
Relevant part of backtrace:
```
#0  0x00007fffef7ef9f7 in get_datetime () from /usr/lib64/python2.7/site-packages/createrepo_c/_createrepo_c.so
#1  0x00007ffff7a5682e in getset_get () from /lib64/libpython2.7.so.1.0
```

It's not 100% reproducible, looks like it's caused by a race condition.
I'll try to get a reliable reproducer or more data.

**Comment by dmach** [comment]
It's not a race condifion after all, it's caused by date handling.
Reproducer:
```
import createrepo_c as cr
uinfo = cr.UpdateInfo("test.xml")
for update in uinfo.updates:
    print update.id
    print update.issued_date
```

Test data (test.xml):
```
<?xml version="1.0" encoding="UTF-8"?>
<updates>
    <update>
        <id>RHxx-2017:0001</id>
        <issued date="2017-01-01" />
    </update>
</updates>
```

When issued date is set to "2017-01-01 00:00:00", the SIGSEGV disappears.

**Comment by Tojaj** [comment]
This bug is caused by Pull Request #4
