### ISSUE TITLE
mergerepo_c and may be broken own workflow ?

### ISSUE THREAD

**Issue by vtolstov** [rpm-software-management/createrepo_c#74]
I have ci system that build packages and upload artifacts to openstack swift.
So for example i have pkg-example that produces example-0.0.1.rpm and example-libs-0.0.1.rpm inside /repo/x86_64/

each step runs on docker container that does not have persistent storage and after container dies data removed...

1) i generate rpmmd  via createrepo_c inside /repo/repodata
2) upload /repo to openstack swift to public/staging/example/ (so i can add this via repo and test package on all my systems without affecting other test nodes
3) if testing on some nodes are fine, i do mergerepo_c with --repo url that points to public/staging and public/staging/example with output to /repo and upload /repo to public/staging/ (so on this step all staging nodes see the package and i can test on more nodes)
4) if testing on all staging nodes are fine i do upload resulted rpms on public/release/example
and do mergerepo_c with --repo pointed to public/release/ and public/release/example.
So all production nodes sees that new package.

My problem - mergerepo_c sees that public/release have older package version and in resulted metadata present only this old version, that absent from public/release/example/.
I can use --all switch, but in this case in metadata i have all package versions, that are stalre already and may be cleanup..

I can rsync all the time packages to use createrepo_c --update because it expensive (i think)
How can i deal with my workflow or how can i change it...?

P.S. I know about mounting openstack swift container via fuse, but i'm try to avoid it because in this case i need privileged docker container (to access to /dev/fuse)

**Comment by kontura** [comment]
I am sorry for the late reply, but I am not sure I understand the problem, you would like a new merge method for mergerepo_c?
I think the merge methods didn't use to be documented, but mergerepo_c provides (described in the man page):
```
       Available merge methods:
       repo
          (default) select package from the first specified repository.
       nvr
          select package with the higher version and release.
       ts
          select package with the newest timestamp.
```

If this issue is still valid and none of the current methods work for you, can you please describe what kind of method do you need and how should it behave?

**Comment by kontura** [comment]
I am closing this for now, if you are still interested please reopen the issue.
