### ISSUE TITLE
Handle older release/version and obsoleted rpms

### ISSUE THREAD

**Issue by tpgxyz** [rpm-software-management/createrepo_c#86]
It really would be nice if createrepo_c have functionality to compare files when creating repodata and allow to remove files if:
- already existing NVRA is older than new NVRA
- already existing rpm  (foo-1.0) file is obsoleted by another rpm (baz-2.0) file i.e.

baz.spec
Obsoletes: foo < 2

**Comment by j-mracek** [comment]
I am really sorry but the report is seems to me to be to specific.
