### ISSUE TITLE
Building on Alpine 3.7

### ISSUE THREAD

**Issue by gdhgdhgdh** [rpm-software-management/createrepo_c#88]
Thanks for the software - here's a one-liner to add the dependencies to get a set of working binaries in `src/*_c` on Docker image `alpine:3.7`. Docs / tests not included.

```
apk --update add bzip2-dev cmake expat-dev file-dev glib-dev curl-dev libxml2-dev python2-dev rpm-dev openssl-dev sqlite-dev xz-dev zlib-dev musl-dev make gcc
```

**Comment by j-mracek** [comment]
I am sorry but I am not sure what is requested. In case that there is still an interest, don't hesitate to reopen it with additional information.
