### ISSUE TITLE
mergerepo_c does not work for private repositories.

### ISSUE THREAD

**Issue by Setheck** [rpm-software-management/createrepo_c#97]
I have a private repository of which I have a .repo file containing credentials installed into /etc/yum.repos.d/ and have verified using yum commands works for seeing and retrieving packages.
However, when trying to merge this repo with a locally created repo. 
I get the following error
`C_CREATEREPOLIB: Critical: cr_get_remote_metadata: curl_easy_perform failed: HTTP response code said error: The requested URL returned error: 401 Unauthorized
Warning: Downloading of repodata failed: https://MY.PRIVATE.REPO`

It appears that mergerepo_c does not go through typical repo mechanisms for retrieving credentials via the repo file. Is there a way to provide credentials or specify that one or more of the repos is private and should be accessed via information in the .repo file?

**Comment by Setheck** [comment]
I was able to use the workaround of providing my creds directly to the request
ex --repo=https://<USER>:<PASS>@MY.PRIVATE.REPO
but this is not ideal for my use case.

**Comment by kontura** [comment]
I am sorry for the late reply but we don't plan to support getting data from `.repo` files. I think the workaround you described is pretty much the way to do it. 

There is no other way to supply the credentials via mergerepo_c.

**Comment by Setheck** [comment]
No worries, thanks for following up.
