### ISSUE TITLE
Package createrepo_c for PyPI

### ISSUE THREAD

**Issue by dkliban** [rpm-software-management/createrepo_c#99]
[Pulp](https://pulpproject.org) depends on createrepo_c to generate RPM repository metadata. Having a package available on PyPI would enable Pulp to manage RPM repositories on non-PRM based Linux distributions. 
This work was started here: https://github.com/rpm-software-management/createrepo_c/pull/96
However, the author ran into some problems that may already be resolved. https://groups.google.com/forum/#!topic/scikit-build/XYfZFT2iFJM

**Comment by Conan-Kudo** [comment]
There's no way to put the Python bindings into PyPI right now while there's no way to plug CMake into a python wheel building process.

**Comment by dralley** [comment]
@Conan-Kudo Not true, there's scikit-build which fills that void.

My PR is mostly working (https://github.com/rpm-software-management/createrepo_c/pull/96) but I'm still working through some kinks.  bdists work fine but sdists are broken.

**Comment by dralley** [comment]
@dkliban @Conan-Kudo 

New PR https://github.com/rpm-software-management/createrepo_c/pull/103.  Everything that I've tested so far works.  I'll be a bit more thorough with testing it tomorrow, and a third party from the scikit-build team is going to double check one of the commits as well.

You may prefer to split some of the changes out into other PRs, which would be no problem for me.

**Comment by goosemania** [comment]
This is resolved by Pulp team and can be closed.
PR #103 is merged, [bindings are published on PyPI](https://pypi.org/project/createrepo-c/).
